import { TransactionData } from '@/lib/types';

// Mock data for the dashboard — will be replaced by API calls
export const MOCK_TRANSACTIONS: TransactionData[] = [
    {
        _id: '1',
        amount: 124.50,
        type: 'expense',
        date: new Date().toISOString(),
        category: 'Groceries',
        description: 'Whole Foods Market',
        paymentMethod: 'Chase Sapphire',
        isRecurring: false,
        icon: 'shopping_cart',
    },
    {
        _id: '2',
        amount: 45.00,
        type: 'expense',
        date: new Date(Date.now() - 86400000).toISOString(),
        category: 'Gas',
        description: 'Shell Station',
        paymentMethod: 'Amex Gold',
        isRecurring: false,
        icon: 'local_gas_station',
    },
    {
        _id: '3',
        amount: 1200.00,
        type: 'income',
        date: new Date(Date.now() - 2 * 86400000).toISOString(),
        category: 'Income',
        description: 'Freelance Payment',
        paymentMethod: 'Bank Transfer',
        isRecurring: false,
        icon: 'payments',
    },
    {
        _id: '4',
        amount: 15.99,
        type: 'expense',
        date: new Date(Date.now() - 3 * 86400000).toISOString(),
        category: 'Entertainment',
        description: 'Netflix Subscription',
        paymentMethod: 'Chase Sapphire',
        isRecurring: true,
        icon: 'movie',
    },
    {
        _id: '5',
        amount: 68.40,
        type: 'expense',
        date: new Date(Date.now() - 5 * 86400000).toISOString(),
        category: 'Food',
        description: 'Sushi Place',
        paymentMethod: 'Cash',
        isRecurring: false,
        icon: 'restaurant',
    },
    {
        _id: '6',
        amount: 24.00,
        type: 'expense',
        date: new Date(Date.now() - 7 * 86400000).toISOString(),
        category: 'Transport',
        description: 'Uber Ride',
        paymentMethod: 'Amex Gold',
        isRecurring: false,
        icon: 'directions_car',
    },
    {
        _id: '7',
        amount: 4200.00,
        type: 'income',
        date: new Date(Date.now() - 8 * 86400000).toISOString(),
        category: 'Salary',
        description: 'Salary Deposit',
        paymentMethod: 'Bank Transfer',
        isRecurring: true,
        icon: 'account_balance',
    },
    {
        _id: '8',
        amount: 89.99,
        type: 'expense',
        date: new Date(Date.now() - 12 * 86400000).toISOString(),
        category: 'Shopping',
        description: 'Amazon Purchase',
        paymentMethod: 'Amex Gold',
        isRecurring: false,
        icon: 'shopping_bag',
    },
    {
        _id: '9',
        amount: 120.00,
        type: 'expense',
        date: new Date(Date.now() - 15 * 86400000).toISOString(),
        category: 'Utilities',
        description: 'Electric Bill',
        paymentMethod: 'Bank Transfer',
        isRecurring: true,
        icon: 'bolt',
    },
    {
        _id: '10',
        amount: 10.99,
        type: 'expense',
        date: new Date(Date.now() - 11 * 86400000).toISOString(),
        category: 'Entertainment',
        description: 'Spotify Premium',
        paymentMethod: 'Chase Sapphire',
        isRecurring: true,
        icon: 'music_note',
    },
];

export const MOCK_MONTHLY_TREND = [
    { date: 'Nov 1', income: 500, expenses: 200 },
    { date: 'Nov 5', income: 600, expenses: 350 },
    { date: 'Nov 10', income: 800, expenses: 450 },
    { date: 'Nov 15', income: 1200, expenses: 600 },
    { date: 'Nov 20', income: 1800, expenses: 900 },
    { date: 'Nov 25', income: 2500, expenses: 1400 },
    { date: 'Nov 30', income: 3200, expenses: 2100 },
];

export const MOCK_CATEGORY_BREAKDOWN = [
    { name: 'Food', total: 840, color: '#10b981', percentage: 40 },
    { name: 'Shopping', total: 525, color: '#3b82f6', percentage: 25 },
    { name: 'Transport', total: 420, color: '#f97316', percentage: 20 },
    { name: 'Others', total: 315, color: '#94a3b8', percentage: 15 },
];

export const MOCK_SUBSCRIPTIONS = [
    {
        _id: 's1',
        name: 'Netflix',
        category: 'Entertainment',
        amount: 15.99,
        frequency: 'monthly' as const,
        nextDueDate: new Date().toISOString(),
        autopay: true,
        status: 'active' as const,
        icon: 'movie',
        color: '#ef4444',
    },
    {
        _id: 's2',
        name: 'Internet Bill',
        category: 'Utilities',
        amount: 89.00,
        frequency: 'monthly' as const,
        nextDueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
        autopay: true,
        status: 'active' as const,
        icon: 'wifi',
        color: '#3b82f6',
    },
    {
        _id: 's3',
        name: "Gold's Gym",
        category: 'Health',
        amount: 45.00,
        frequency: 'monthly' as const,
        nextDueDate: new Date(Date.now() + 8 * 86400000).toISOString(),
        autopay: false,
        status: 'active' as const,
        icon: 'fitness_center',
        color: '#f97316',
    },
    {
        _id: 's4',
        name: 'Adobe Creative',
        category: 'Software',
        amount: 54.99,
        frequency: 'monthly' as const,
        nextDueDate: new Date(Date.now() + 15 * 86400000).toISOString(),
        autopay: true,
        status: 'active' as const,
        icon: 'design_services',
        color: '#a855f7',
    },
    {
        _id: 's5',
        name: 'Spotify',
        category: 'Entertainment',
        amount: 9.99,
        frequency: 'monthly' as const,
        nextDueDate: new Date(Date.now() + 25 * 86400000).toISOString(),
        autopay: true,
        status: 'active' as const,
        icon: 'music_note',
        color: '#10b981',
    },
];
